### ISSUE TITLE
Unable to locate config file or config directory

### ISSUE THREAD

**Issue by zaimazhar97** [lowply/build-hugo#11]
Hi...
Pretty new to this but how should I resolve this? Thanks!
![image](https://user-images.githubusercontent.com/54124001/82295410-4fe09b80-99e2-11ea-9010-396c93ad55f1.png)

**Comment by lowply** [comment]
@zaimazhar97 👋🏻 You don't seem to have a Hugo site created in your repository. See [Quick Start | Hugo](https://gohugo.io/getting-started/quick-start/) to create one.
